// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("System.Data.SqlClient.Extensions.ReaderWrapper")]
[assembly: AssemblyDescription("ReaderWrapper Extension for System.Data.SqlClient")]
[assembly: Guid("0E1ECA29-37B2-4AA8-821C-9835856B98C7")]
[assembly: AssemblyProduct("ReaderWrapper")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "System.Data.SqlClient.Extensions.ReaderWrapper";
        internal const System.String AssemblyDescription = "ReaderWrapper Extension for System.Data.SqlClient";
        internal const System.String Guid = "0E1ECA29-37B2-4AA8-821C-9835856B98C7";
        internal const System.String AssemblyProduct = "ReaderWrapper";
        internal const System.String AssemblyVersion = "1.0.0";
        internal const System.String AssemblyFileVersion = "1.0.0";
    }
}
